/*
 * Copyright (c) 2010-2026 GraphDefined GmbH <achim.friedland@graphdefined.com>
 * This file is part of Vanaheimr Hermod <https://www.github.com/Vanaheimr/Hermod>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#region Usings

using System.Security.Cryptography;

using NUnit.Framework;

using org.GraphDefined.Vanaheimr.Hermod;
using org.GraphDefined.Vanaheimr.Hermod.SSH;
using org.GraphDefined.Vanaheimr.Hermod.SSH.Client;

#endregion

namespace org.GraphDefined.Vanaheimr.Hermod.SSH.Tests
{

    /// <summary>
    /// <b>Our client against the reference server</b> — the direction the interop program had been
    /// missing all along.
    ///
    /// <para>
    /// Every OpenSSH test until now drove <i>their</i> client against <i>our</i> server, which says
    /// nothing about our client's own KEXINIT, its signature verification, its authentication requests or
    /// its SFTP client. Those had only ever spoken to our own server, or to the small implementations
    /// (Dropbear, TinySSH). Here a real <c>sshd</c> is the judge — including its <c>sftp-server</c>
    /// subsystem, so our SFTP <i>client</i> finally faces OpenSSH's SFTP <i>server</i> rather than ours.
    /// </para>
    ///
    /// <para>
    /// The daemon runs unprivileged on a high port inside WSL, with its own host key and an isolated
    /// authorized-keys file, so nothing of the developer's real SSH setup is touched or consulted.
    /// </para>
    /// </summary>
    [TestFixture]
    [Category("Interop")]
    [Category("Interop.WSL")]
    [Category("Interop.OpenSSH")]
    public class OpenSshServerInteropTests
    {

        #region (private) harness

        private const String Marker = "OPENSSH_SERVER_INTEROP_OK";

        private sealed record Daemon(WslServer Server, Int32 Port, Byte[] HostKeyBlob, ISshHostKey UserKey, String WslRoot, String WindowsRoot);


        /// <summary>
        /// Start an unprivileged <c>sshd</c> that trusts exactly one key: the one we just generated.
        /// </summary>
        /// <param name="WithSftp">Also offer the <c>sftp</c> subsystem.</param>
        private static async Task<Daemon> StartSshdAsync(CancellationToken CancellationToken, Boolean WithSftp = false)
        {

            WslInterop.SkipIfUnavailable();

            var identifier  = Guid.NewGuid().ToString("N");
            var windowsRoot = Path.Combine(Path.GetTempPath(), "hermod_sshd_" + identifier);
            Directory.CreateDirectory(windowsRoot);

            var userKey = SshHostKey.GenerateEd25519();
            await SshKeyGenerator.WriteKeyPairAsync(userKey, Path.Combine(windowsRoot, "user"), "sshd-interop", CancellationToken);

            var home    = await WslInterop.HomeAsync(CancellationToken);
            var wslRoot = $"{home}/.hermod-interop/sshd_{identifier}";
            var staging = WslInterop.ToWslPath(windowsRoot);

            // sshd insists on sane permissions even with StrictModes off for some paths, and the host key
            // must be its own — generated by ssh-keygen so nothing about this test depends on our writer.
            var (prepared, _, prepareError) = await WslInterop.RunAsync([
                                                  "-e", "bash", "-c",
                                                  $"mkdir -p {wslRoot} && chmod 700 {wslRoot} && " +
                                                  $"cp {staging}/user.pub {wslRoot}/authorized_keys && " +
                                                  $"chmod 600 {wslRoot}/authorized_keys && " +
                                                  $"ssh-keygen -t ed25519 -f {wslRoot}/hostkey -N '' -q"
                                              ], CancellationToken);

            if (prepared != 0)
                Assert.Ignore($"Could not prepare the sshd workspace: {prepareError}");

            var (printed, hostKeyText, printError) = await WslInterop.RunAsync([
                                                         "-e", "ssh-keygen", "-y", "-f", $"{wslRoot}/hostkey"
                                                     ], CancellationToken);

            if (printed != 0)
                Assert.Ignore($"Could not read the sshd host key: {printError}");

            var hostKeyBlob = Convert.FromBase64String(
                                  hostKeyText.Split('\n')
                                             .First(line => line.StartsWith("ssh-ed25519", StringComparison.Ordinal))
                                             .Split(' ')[1]);

            var port      = FreePort();
            var subsystem = WithSftp ? "-o Subsystem=\"sftp /usr/lib/openssh/sftp-server\" " : "";

            // The mkdir rides inside the command substitution: run as root, sshd refuses to start
            // without the privilege-separation directory /run/sshd, and /run is a tmpfs — a fresh CI
            // container or a rebooted machine has no /run/sshd until something creates it. Run as an
            // ordinary user the mkdir fails (silently, hence 2>/dev/null), and an unprivileged sshd
            // does not want the directory in the first place.
            var daemon = await WslInterop.StartServerAsync(
                             $"$(mkdir -p /run/sshd 2>/dev/null; command -v sshd || echo /usr/sbin/sshd) -D -e -p {port} " +
                             $"-h {wslRoot}/hostkey " +
                             $"-o AuthorizedKeysFile={wslRoot}/authorized_keys " +
                             $"-o StrictModes=no -o UsePAM=no -o PidFile=none " +
                             $"-o PasswordAuthentication=no -o KbdInteractiveAuthentication=no " +
                             subsystem +
                             $"-o ListenAddress=127.0.0.1",
                             port,
                             CancellationToken);

            return new Daemon(daemon, port, hostKeyBlob, userKey, wslRoot, windowsRoot);

        }

        private static async Task StopAsync(Daemon Daemon)
        {
            await Daemon.Server.DisposeAsync();
            try { Directory.Delete(Daemon.WindowsRoot, recursive: true); } catch { }
            try { await WslInterop.RunAsync(["-e", "rm", "-rf", Daemon.WslRoot], CancellationToken.None); } catch { }
        }

        private static Int32 FreePort()
        {
            using var probe = new System.Net.Sockets.TcpListener(System.Net.IPAddress.Loopback, 0);
            probe.Start();
            var port = ((System.Net.IPEndPoint) probe.LocalEndpoint).Port;
            probe.Stop();
            return port;
        }

        /// <summary>The user sshd will authenticate — it runs unprivileged, so only its own account.</summary>
        private static Task<String> WhoAsync(CancellationToken CancellationToken)
            => WslInterop.WhoAmIAsync(CancellationToken);

        #endregion


        #region OurClient_RunsCommand_OnRealOpenSshServer

        /// <summary>
        /// The acceptance test for our client: it verifies OpenSSH's host key, authenticates with a key our
        /// own generator wrote, opens a session and reads back what the remote shell printed — all judged by
        /// the implementation everyone else is measured against.
        /// </summary>
        [Test]
        [CancelAfter(120000)]
        public async Task OurClient_RunsCommand_OnRealOpenSshServer(CancellationToken CancellationToken)
        {

            var daemon = await StartSshdAsync(CancellationToken);
            var user   = await WhoAsync(CancellationToken);

            try
            {

                await using var client = await SshClient.ConnectAsync(
                                             "127.0.0.1",
                                             (UInt16) daemon.Port,
                                             new SshClientOptions {
                                                 Username      = user,
                                                 Credentials   = [ daemon.UserKey ],
                                                 VerifyHostKey = blob => blob.AsSpan().SequenceEqual(daemon.HostKeyBlob)
                                             },
                                             CancellationToken);

                var result = await client.ExecuteAsync($"echo {Marker}", CancellationToken);

                TestContext.Out.WriteLine($"sshd replied: {result.StandardOutput.Trim()} (exit {result.ExitCode})");

                Assert.Multiple(() => {
                    Assert.That(result.StandardOutput, Does.Contain(Marker),
                                $"our client must read the remote command's output.\n{daemon.Server.Output}");
                    Assert.That(result.ExitCode, Is.EqualTo(0), "and must see the remote exit status");
                });

            }
            finally
            {
                await StopAsync(daemon);
            }

        }

        #endregion

        #region OurClient_SeesRemoteExitStatus_FromRealOpenSshServer

        /// <summary>A failing remote command: the exit status has to survive the trip back.</summary>
        [Test]
        [CancelAfter(120000)]
        public async Task OurClient_SeesRemoteExitStatus_FromRealOpenSshServer(CancellationToken CancellationToken)
        {

            var daemon = await StartSshdAsync(CancellationToken);
            var user   = await WhoAsync(CancellationToken);

            try
            {

                await using var client = await SshClient.ConnectAsync(
                                             "127.0.0.1",
                                             (UInt16) daemon.Port,
                                             new SshClientOptions {
                                                 Username      = user,
                                                 Credentials   = [ daemon.UserKey ],
                                                 VerifyHostKey = blob => blob.AsSpan().SequenceEqual(daemon.HostKeyBlob)
                                             },
                                             CancellationToken);

                var result = await client.ExecuteAsync("exit 42", CancellationToken);

                Assert.That(result.ExitCode, Is.EqualTo(42),
                            $"OpenSSH's exit-status request must reach our client.\n{daemon.Server.Output}");

            }
            finally
            {
                await StopAsync(daemon);
            }

        }

        #endregion

        #region OurSftpClient_TransfersFiles_WithRealSftpServer

        /// <summary>
        /// Our SFTP <b>client</b> against OpenSSH's <c>sftp-server</c> — the mirror of the existing test
        /// where their <c>sftp</c> CLI drives our subsystem. Until now our client had only ever spoken to
        /// our own SFTP server, so nothing proved our INIT/OPEN/WRITE/READ/CLOSE sequence against the
        /// reference implementation.
        /// </summary>
        [Test]
        [CancelAfter(120000)]
        public async Task OurSftpClient_TransfersFiles_WithRealSftpServer(CancellationToken CancellationToken)
        {

            var daemon = await StartSshdAsync(CancellationToken, WithSftp: true);
            var user   = await WhoAsync(CancellationToken);

            var payload = RandomNumberGenerator.GetBytes(40_000);   // multi-chunk
            var remote  = $"{daemon.WslRoot}/payload.bin";

            try
            {

                await using var client = await SshClient.ConnectAsync(
                                             "127.0.0.1",
                                             (UInt16) daemon.Port,
                                             new SshClientOptions {
                                                 Username      = user,
                                                 Credentials   = [ daemon.UserKey ],
                                                 VerifyHostKey = blob => blob.AsSpan().SequenceEqual(daemon.HostKeyBlob)
                                             },
                                             CancellationToken);

                var sftp = await client.OpenSftpClientAsync(CancellationToken);

                await sftp.UploadAsync(remote, payload, CancellationToken);
                var downloaded = await sftp.DownloadAsync(remote, CancellationToken);
                var listing    = await sftp.ListDirectoryAsync(daemon.WslRoot, CancellationToken);

                TestContext.Out.WriteLine($"our SFTP client listed {listing.Count} entries on OpenSSH's sftp-server");

                Assert.Multiple(() => {
                    Assert.That(downloaded, Is.EqualTo(payload),
                                $"the round-trip through OpenSSH's sftp-server must be byte-for-byte.\n{daemon.Server.Output}");
                    Assert.That(listing.Select(entry => entry.Name), Does.Contain("payload.bin"));
                });

            }
            finally
            {
                await StopAsync(daemon);
            }

        }

        #endregion

        #region OurClient_CompletesTransport_WithRealOpenSshServer

        /// <summary>
        /// The key-exchange matrix in the client role: our client offers exactly one method and OpenSSH
        /// must agree on it. The server-side matrix has covered these for a long time; this is the first
        /// time our <i>client</i>'s exchange-hash computation and host-key signature verification are
        /// judged by the reference implementation, one method at a time.
        /// </summary>
        [Test]
        [CancelAfter(120000)]
        [TestCase("curve25519-sha256")]
        [TestCase("ecdh-sha2-nistp256")]
        [TestCase("ecdh-sha2-nistp521")]
        // Deliberately no diffie-hellman-group14/16: OpenSSH 10.0 dropped finite-field DH from the
        // *server* defaults (it remains a client default), so those cases would be testing sshd's
        // configuration rather than our interoperability. The server-role matrix still covers them,
        // because there we are the ones offering.
        [TestCase("mlkem768x25519-sha256")]
        [TestCase("sntrup761x25519-sha512@openssh.com")]
        public async Task OurClient_CompletesTransport_WithRealOpenSshServer(String KeyExchange, CancellationToken CancellationToken)
        {

            var daemon = await StartSshdAsync(CancellationToken);

            try
            {

                var pipe = await SshTcp.ConnectAsync(new IPSocket(IPv4Address.Localhost, IPPort.Parse(daemon.Port)), CancellationToken);

                using var transport = await SshTransport.ClientHandshakeAsync(
                                          pipe,
                                          VerifyHostKey: blob => blob.AsSpan().SequenceEqual(daemon.HostKeyBlob),
                                          KeyExchanges:  [ KeyExchange ],
                                          CancellationToken: CancellationToken);

                var algorithms = transport.Algorithms;

                TestContext.Out.WriteLine($"sshd agreed on {algorithms.KeyExchange} / {algorithms.CipherServerToClient} / {algorithms.HostKey}");

                Assert.Multiple(() => {
                    Assert.That(algorithms.KeyExchange, Is.EqualTo(KeyExchange),
                                $"our client must complete {KeyExchange} with a real sshd.\n{daemon.Server.Output}");
                    Assert.That(algorithms.StrictKex, Is.True,
                                "OpenSSH has offered strict KEX since 9.6, so the Terrapin countermeasure must be in force");
                });

                await pipe.Output.CompleteAsync();
                await pipe.Input. CompleteAsync();

            }
            finally
            {
                await StopAsync(daemon);
            }

        }

        #endregion

        #region OurClient_RejectsAWrongOpenSshHostKey

        /// <summary>
        /// Our client must fail closed against the reference implementation too — the same promise the
        /// Dropbear and TinySSH tests make, checked against the server everyone else is measured by.
        /// </summary>
        [Test]
        [CancelAfter(120000)]
        public async Task OurClient_RejectsAWrongOpenSshHostKey(CancellationToken CancellationToken)
        {

            var daemon       = await StartSshdAsync(CancellationToken);
            var user         = await WhoAsync(CancellationToken);
            var somebodyElse = SshHostKey.GenerateEd25519();

            try
            {

                Assert.That(async () => await SshClient.ConnectAsync(
                                            "127.0.0.1",
                                            (UInt16) daemon.Port,
                                            new SshClientOptions {
                                                Username      = user,
                                                Credentials   = [ daemon.UserKey ],
                                                VerifyHostKey = blob => blob.AsSpan().SequenceEqual(somebodyElse.PublicKeyBlob)
                                            },
                                            CancellationToken),
                            Throws.TypeOf<SshWireException>(),
                            "our client must refuse a host key that is not the one it pinned");

            }
            finally
            {
                await StopAsync(daemon);
            }

        }

        #endregion

    }

}
